# Generated by Django 5.0.4 on 2024-05-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=13)),
            ],
        ),
    ]
